/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import java.security.GeneralSecurityException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.mail.NoSuchProviderException;
import javax.swing.JOptionPane;

/**
 *
 * @author Philippe
 */
public class LoginFrame extends javax.swing.JFrame
{
    private final Application_EMail mainFrame;
    /**
     * Creates new form LoginFrame
     * @param mf
     */
    public LoginFrame(Application_EMail mf)
    {
        this.mainFrame = mf;
        
        initComponents();
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTextField1 = new javax.swing.JTextField();
        jLabelLogin = new javax.swing.JLabel();
        jLabelPWD = new javax.swing.JLabel();
        jButton_Connexion = new javax.swing.JButton();
        jButton_Effacer = new javax.swing.JButton();
        jTF_Login = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton_Bypass = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Application_EMail - Connexion");
        setResizable(false);

        jLabelLogin.setText("Nom d'utilisateur :");

        jLabelPWD.setText("Mot de passe :");

        jButton_Connexion.setText("Connexion");
        jButton_Connexion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_ConnexionActionPerformed(evt);
            }
        });

        jButton_Effacer.setText("Effacer");
        jButton_Effacer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_EffacerActionPerformed(evt);
            }
        });

        jTF_Login.setText("dimartino");

        jPasswordField.setText("123Soleil");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Connexion");

        jButton_Bypass.setText("ByPass");
        jButton_Bypass.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_BypassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLogin)
                            .addComponent(jLabelPWD))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_Login)
                            .addComponent(jPasswordField))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_Bypass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Connexion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Effacer)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogin)
                    .addComponent(jTF_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPWD)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Connexion)
                    .addComponent(jButton_Effacer)
                    .addComponent(jButton_Bypass))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ConnexionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_ConnexionActionPerformed
    {//GEN-HEADEREND:event_jButton_ConnexionActionPerformed
        if (jTF_Login.getText().isEmpty() || jPasswordField.getPassword().length == 0)
        {
            JOptionPane.showMessageDialog(this, "L'adresse mail et/ou le mot de passe est vide !", "Attention", JOptionPane.WARNING_MESSAGE);
            jPasswordField.setText(null);
        }
        else
        {
            try
            {
                mainFrame.Connect(jTF_Login.getText(), String.valueOf(jPasswordField.getPassword()));
                mainFrame.ChargementEmailsListe();
                this.dispose();
                mainFrame.setVisible(true);
            }
            catch(NoSuchProviderException ex) 
            {
                JOptionPane.showMessageDialog(this, "Impossible de trouver un provider !", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
            catch (MessagingException ex) 
            {
                ex.printStackTrace();
                if(ex.getMessage().equals("[AUTH] Username and password not accepted."))
                    JOptionPane.showMessageDialog(this, "L'adresse mail et/ou le mot de passe est incorrect !", "Erreur", JOptionPane.ERROR_MESSAGE);
                else
                    JOptionPane.showMessageDialog(this, "Impossible de se connecter !", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
            catch (GeneralSecurityException ex)
            {
                ex.printStackTrace();
                Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton_ConnexionActionPerformed

    private void jButton_EffacerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_EffacerActionPerformed
    {//GEN-HEADEREND:event_jButton_EffacerActionPerformed
        jTF_Login.setText(null);
        jPasswordField.setText(null);
    }//GEN-LAST:event_jButton_EffacerActionPerformed

    private void jButton_BypassActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_BypassActionPerformed
    {//GEN-HEADEREND:event_jButton_BypassActionPerformed
        mainFrame.ChargementEmailsListe();
        this.dispose();
        mainFrame.setVisible(true);
    }//GEN-LAST:event_jButton_BypassActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Bypass;
    private javax.swing.JButton jButton_Connexion;
    private javax.swing.JButton jButton_Effacer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelPWD;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTF_Login;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
