/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Philippe
 */
public class SendMailPanel extends javax.swing.JPanel
{
    private final JPanel parent;
    private final JButton buttonSend;
    /**
     * Creates new form NewJPanel
     * @param parent
     * @param buttonSend
     */
    public SendMailPanel(JPanel parent, JButton buttonSend)
    {
        this.buttonSend = buttonSend;
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTF_SendTo = new javax.swing.JTextField();
        jTF_Subject = new javax.swing.JTextField();
        jButton_Add_Attachments = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA_Message = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Subject = new javax.swing.JLabel();
        jCB_Attachments = new javax.swing.JComboBox<>();
        jButton_Send = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();

        jButton_Add_Attachments.setText("Ajouter une pièce jointe");

        jTA_Message.setColumns(20);
        jTA_Message.setRows(5);
        jScrollPane1.setViewportView(jTA_Message);

        jLabel1.setText("À :");

        jLabel_Subject.setText("Objet :");

        jButton_Send.setText("Envoyer");

        jButton_Cancel.setText("Annuler");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Add_Attachments)
                        .addGap(18, 18, 18)
                        .addComponent(jCB_Attachments, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Subject)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_SendTo)
                            .addComponent(jTF_Subject))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jButton_Send)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Cancel)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cancel)
                    .addComponent(jButton_Send))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_SendTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Subject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Add_Attachments)
                    .addComponent(jCB_Attachments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_CancelActionPerformed
    {//GEN-HEADEREND:event_jButton_CancelActionPerformed
       parent.removeAll();
       parent.repaint();
       buttonSend.setEnabled(true);
    }//GEN-LAST:event_jButton_CancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_Attachments;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Send;
    private javax.swing.JComboBox<String> jCB_Attachments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Subject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTA_Message;
    private javax.swing.JTextField jTF_SendTo;
    private javax.swing.JTextField jTF_Subject;
    // End of variables declaration//GEN-END:variables
}
